version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./source:/app
      - /app/node_modules
    environment:
      - GO_ENV=development
    command: go run main.go
